spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2}
    username: ${MYSQL_USERNAME:db}
    password: ${MYSQL_PASSWORD:db}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    connect-retries: 5
    enabled: true

springdoc:
  swagger-ui:
    doc-expansion: none
    enabled: ${SWAGGER_UI_ENABLED:true}

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        same-site: lax
        max-age: 30d
        name: JSESSIONID
      timeout: 30d
  forward-headers-strategy: framework
  reactive:
    session:
      timeout: 3h

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/base/*Mapper.xml
    - classpath:/db/mapper/extend/*Mapper.xml

application:
  name: cap
  version: 1.0.0-SNAPSHOT

ip-address-whitelist:
  healthcheck-api:
    - 127.0.0.1
    - ::1
docker:
  host: ${DOCKER_HOST:tcp://localhost:2375}
