package net.averak.cap.adapter.dao.entity.base;

import javax.annotation.Nonnull;

public class CronJobEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.id
     *
     * @mbg.generated
     */
    @Nonnull
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.project_id
     *
     * @mbg.generated
     */
    @Nonnull
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.expression
     *
     * @mbg.generated
     */
    @Nonnull
    private String expression;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.command
     *
     * @mbg.generated
     */
    @Nonnull
    private String command;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.docker_image_url
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.docker_image_tag
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageTag;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    public CronJobEntity(String id, String projectId, String expression, String command, String dockerImageUrl, String dockerImageTag) {
        this.id = id;
        this.projectId = projectId;
        this.expression = expression;
        this.command = command;
        this.dockerImageUrl = dockerImageUrl;
        this.dockerImageTag = dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.id
     *
     * @return the value of cron_job.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.project_id
     *
     * @return the value of cron_job.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.expression
     *
     * @return the value of cron_job.expression
     *
     * @mbg.generated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.command
     *
     * @return the value of cron_job.command
     *
     * @mbg.generated
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.docker_image_url
     *
     * @return the value of cron_job.docker_image_url
     *
     * @mbg.generated
     */
    public String getDockerImageUrl() {
        return dockerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.docker_image_tag
     *
     * @return the value of cron_job.docker_image_tag
     *
     * @mbg.generated
     */
    public String getDockerImageTag() {
        return dockerImageTag;
    }
}
