package net.averak.cap.adapter.dao.entity.base;

import javax.annotation.Nonnull;

public class CronJobEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.id
     *
     * @mbg.generated
     */
    @Nonnull
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.project_id
     *
     * @mbg.generated
     */
    @Nonnull
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.expression
     *
     * @mbg.generated
     */
    @Nonnull
    private String expression;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.command
     *
     * @mbg.generated
     */
    @Nonnull
    private String command;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.docker_image_url
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.docker_image_tag
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageTag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cron_job.container_environment_variables
     *
     * @mbg.generated
     */
    @Nonnull
    private String containerEnvironmentVariables;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    public CronJobEntity(String id, String projectId, String expression, String command, String dockerImageUrl, String dockerImageTag) {
        this.id = id;
        this.projectId = projectId;
        this.expression = expression;
        this.command = command;
        this.dockerImageUrl = dockerImageUrl;
        this.dockerImageTag = dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    public CronJobEntity(String id, String projectId, String expression, String command, String dockerImageUrl, String dockerImageTag,
        String containerEnvironmentVariables) {
        this.id = id;
        this.projectId = projectId;
        this.expression = expression;
        this.command = command;
        this.dockerImageUrl = dockerImageUrl;
        this.dockerImageTag = dockerImageTag;
        this.containerEnvironmentVariables = containerEnvironmentVariables;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    public CronJobEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.id
     *
     * @return the value of cron_job.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.id
     *
     * @param id the value for cron_job.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.project_id
     *
     * @return the value of cron_job.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.project_id
     *
     * @param projectId the value for cron_job.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.expression
     *
     * @return the value of cron_job.expression
     *
     * @mbg.generated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.expression
     *
     * @param expression the value for cron_job.expression
     *
     * @mbg.generated
     */
    public void setExpression(String expression) {
        this.expression = expression;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.command
     *
     * @return the value of cron_job.command
     *
     * @mbg.generated
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.command
     *
     * @param command the value for cron_job.command
     *
     * @mbg.generated
     */
    public void setCommand(String command) {
        this.command = command;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.docker_image_url
     *
     * @return the value of cron_job.docker_image_url
     *
     * @mbg.generated
     */
    public String getDockerImageUrl() {
        return dockerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.docker_image_url
     *
     * @param dockerImageUrl the value for cron_job.docker_image_url
     *
     * @mbg.generated
     */
    public void setDockerImageUrl(String dockerImageUrl) {
        this.dockerImageUrl = dockerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.docker_image_tag
     *
     * @return the value of cron_job.docker_image_tag
     *
     * @mbg.generated
     */
    public String getDockerImageTag() {
        return dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.docker_image_tag
     *
     * @param dockerImageTag the value for cron_job.docker_image_tag
     *
     * @mbg.generated
     */
    public void setDockerImageTag(String dockerImageTag) {
        this.dockerImageTag = dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cron_job.container_environment_variables
     *
     * @return the value of cron_job.container_environment_variables
     *
     * @mbg.generated
     */
    public String getContainerEnvironmentVariables() {
        return containerEnvironmentVariables;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cron_job.container_environment_variables
     *
     * @param containerEnvironmentVariables the value for cron_job.container_environment_variables
     *
     * @mbg.generated
     */
    public void setContainerEnvironmentVariables(String containerEnvironmentVariables) {
        this.containerEnvironmentVariables = containerEnvironmentVariables;
    }
}
