package net.averak.cap.adapter.dao.entity.base;

import java.time.LocalDateTime;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class MaintenanceEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * maintenance.id
     *
     * @mbg.generated
     */
    @Nonnull
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * maintenance.open_at
     *
     * @mbg.generated
     */
    @Nonnull
    private LocalDateTime openAt;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * maintenance.close_at
     *
     * @mbg.generated
     */
    @Nonnull
    private LocalDateTime closeAt;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * maintenance.memo
     *
     * @mbg.generated
     */
    @Nullable
    private String memo;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    public MaintenanceEntity(String id, LocalDateTime openAt, LocalDateTime closeAt, String memo) {
        this.id = id;
        this.openAt = openAt;
        this.closeAt = closeAt;
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    public MaintenanceEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column maintenance.id
     *
     * @return the value of maintenance.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * maintenance.id
     *
     * @param id the value for maintenance.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column maintenance.open_at
     *
     * @return the value of maintenance.open_at
     *
     * @mbg.generated
     */
    public LocalDateTime getOpenAt() {
        return openAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * maintenance.open_at
     *
     * @param openAt the value for maintenance.open_at
     *
     * @mbg.generated
     */
    public void setOpenAt(LocalDateTime openAt) {
        this.openAt = openAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column maintenance.close_at
     *
     * @return the value of maintenance.close_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCloseAt() {
        return closeAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * maintenance.close_at
     *
     * @param closeAt the value for maintenance.close_at
     *
     * @mbg.generated
     */
    public void setCloseAt(LocalDateTime closeAt) {
        this.closeAt = closeAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column maintenance.memo
     *
     * @return the value of maintenance.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * maintenance.memo
     *
     * @param memo the value for maintenance.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}
