package net.averak.cap.adapter.dao.entity.base;

import javax.annotation.Nonnull;

public class ProjectEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.id
     *
     * @mbg.generated
     */
    @Nonnull
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.name
     *
     * @mbg.generated
     */
    @Nonnull
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.docker_image_url
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.docker_image_tag
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageTag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.container_port
     *
     * @mbg.generated
     */
    @Nonnull
    private Integer containerPort;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.host_port
     *
     * @mbg.generated
     */
    @Nonnull
    private Integer hostPort;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    public ProjectEntity(String id, String name, String dockerImageUrl, String dockerImageTag, Integer containerPort, Integer hostPort) {
        this.id = id;
        this.name = name;
        this.dockerImageUrl = dockerImageUrl;
        this.dockerImageTag = dockerImageTag;
        this.containerPort = containerPort;
        this.hostPort = hostPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.name
     *
     * @return the value of project.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.docker_image_url
     *
     * @return the value of project.docker_image_url
     *
     * @mbg.generated
     */
    public String getDockerImageUrl() {
        return dockerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.docker_image_tag
     *
     * @return the value of project.docker_image_tag
     *
     * @mbg.generated
     */
    public String getDockerImageTag() {
        return dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.container_port
     *
     * @return the value of project.container_port
     *
     * @mbg.generated
     */
    public Integer getContainerPort() {
        return containerPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.host_port
     *
     * @return the value of project.host_port
     *
     * @mbg.generated
     */
    public Integer getHostPort() {
        return hostPort;
    }
}
