package net.averak.cap.adapter.dao.entity.base;

import java.util.ArrayList;
import java.util.List;

public class ProjectCronJobExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public ProjectCronJobExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExpressionIsNull() {
            addCriterion("`expression` is null");
            return (Criteria) this;
        }

        public Criteria andExpressionIsNotNull() {
            addCriterion("`expression` is not null");
            return (Criteria) this;
        }

        public Criteria andExpressionEqualTo(String value) {
            addCriterion("`expression` =", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionNotEqualTo(String value) {
            addCriterion("`expression` <>", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionGreaterThan(String value) {
            addCriterion("`expression` >", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("`expression` >=", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionLessThan(String value) {
            addCriterion("`expression` <", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionLessThanOrEqualTo(String value) {
            addCriterion("`expression` <=", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionLike(String value) {
            addCriterion("`expression` like", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionNotLike(String value) {
            addCriterion("`expression` not like", value, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionIn(List<String> values) {
            addCriterion("`expression` in", values, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionNotIn(List<String> values) {
            addCriterion("`expression` not in", values, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionBetween(String value1, String value2) {
            addCriterion("`expression` between", value1, value2, "expression");
            return (Criteria) this;
        }

        public Criteria andExpressionNotBetween(String value1, String value2) {
            addCriterion("`expression` not between", value1, value2, "expression");
            return (Criteria) this;
        }

        public Criteria andCommandIsNull() {
            addCriterion("`command` is null");
            return (Criteria) this;
        }

        public Criteria andCommandIsNotNull() {
            addCriterion("`command` is not null");
            return (Criteria) this;
        }

        public Criteria andCommandEqualTo(String value) {
            addCriterion("`command` =", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotEqualTo(String value) {
            addCriterion("`command` <>", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandGreaterThan(String value) {
            addCriterion("`command` >", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandGreaterThanOrEqualTo(String value) {
            addCriterion("`command` >=", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLessThan(String value) {
            addCriterion("`command` <", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLessThanOrEqualTo(String value) {
            addCriterion("`command` <=", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLike(String value) {
            addCriterion("`command` like", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotLike(String value) {
            addCriterion("`command` not like", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandIn(List<String> values) {
            addCriterion("`command` in", values, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotIn(List<String> values) {
            addCriterion("`command` not in", values, "command");
            return (Criteria) this;
        }

        public Criteria andCommandBetween(String value1, String value2) {
            addCriterion("`command` between", value1, value2, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotBetween(String value1, String value2) {
            addCriterion("`command` not between", value1, value2, "command");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlIsNull() {
            addCriterion("`docker_image_url` is null");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlIsNotNull() {
            addCriterion("`docker_image_url` is not null");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlEqualTo(String value) {
            addCriterion("`docker_image_url` =", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlNotEqualTo(String value) {
            addCriterion("`docker_image_url` <>", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlGreaterThan(String value) {
            addCriterion("`docker_image_url` >", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("`docker_image_url` >=", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlLessThan(String value) {
            addCriterion("`docker_image_url` <", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlLessThanOrEqualTo(String value) {
            addCriterion("`docker_image_url` <=", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlLike(String value) {
            addCriterion("`docker_image_url` like", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlNotLike(String value) {
            addCriterion("`docker_image_url` not like", value, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlIn(List<String> values) {
            addCriterion("`docker_image_url` in", values, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlNotIn(List<String> values) {
            addCriterion("`docker_image_url` not in", values, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlBetween(String value1, String value2) {
            addCriterion("`docker_image_url` between", value1, value2, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageUrlNotBetween(String value1, String value2) {
            addCriterion("`docker_image_url` not between", value1, value2, "dockerImageUrl");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagIsNull() {
            addCriterion("`docker_image_tag` is null");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagIsNotNull() {
            addCriterion("`docker_image_tag` is not null");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagEqualTo(String value) {
            addCriterion("`docker_image_tag` =", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagNotEqualTo(String value) {
            addCriterion("`docker_image_tag` <>", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagGreaterThan(String value) {
            addCriterion("`docker_image_tag` >", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagGreaterThanOrEqualTo(String value) {
            addCriterion("`docker_image_tag` >=", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagLessThan(String value) {
            addCriterion("`docker_image_tag` <", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagLessThanOrEqualTo(String value) {
            addCriterion("`docker_image_tag` <=", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagLike(String value) {
            addCriterion("`docker_image_tag` like", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagNotLike(String value) {
            addCriterion("`docker_image_tag` not like", value, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagIn(List<String> values) {
            addCriterion("`docker_image_tag` in", values, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagNotIn(List<String> values) {
            addCriterion("`docker_image_tag` not in", values, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagBetween(String value1, String value2) {
            addCriterion("`docker_image_tag` between", value1, value2, "dockerImageTag");
            return (Criteria) this;
        }

        public Criteria andDockerImageTagNotBetween(String value1, String value2) {
            addCriterion("`docker_image_tag` not between", value1, value2, "dockerImageTag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
