package net.averak.cap.adapter.dao.entity.base;

import javax.annotation.Nonnull;

public class ProjectEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.id
     *
     * @mbg.generated
     */
    @Nonnull
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.name
     *
     * @mbg.generated
     */
    @Nonnull
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.docker_image_url
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.docker_image_tag
     *
     * @mbg.generated
     */
    @Nonnull
    private String dockerImageTag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.container_port
     *
     * @mbg.generated
     */
    @Nonnull
    private Integer containerPort;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.host_port
     *
     * @mbg.generated
     */
    @Nonnull
    private Integer hostPort;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.is_deleted
     *
     * @mbg.generated
     */
    @Nonnull
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * project.container_environment_variables
     *
     * @mbg.generated
     */
    @Nonnull
    private String containerEnvironmentVariables;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    public ProjectEntity(String id, String name, String dockerImageUrl, String dockerImageTag, Integer containerPort, Integer hostPort,
        Boolean isDeleted) {
        this.id = id;
        this.name = name;
        this.dockerImageUrl = dockerImageUrl;
        this.dockerImageTag = dockerImageTag;
        this.containerPort = containerPort;
        this.hostPort = hostPort;
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    public ProjectEntity(String id, String name, String dockerImageUrl, String dockerImageTag, Integer containerPort, Integer hostPort,
        Boolean isDeleted, String containerEnvironmentVariables) {
        this.id = id;
        this.name = name;
        this.dockerImageUrl = dockerImageUrl;
        this.dockerImageTag = dockerImageTag;
        this.containerPort = containerPort;
        this.hostPort = hostPort;
        this.isDeleted = isDeleted;
        this.containerEnvironmentVariables = containerEnvironmentVariables;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    public ProjectEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.name
     *
     * @return the value of project.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.name
     *
     * @param name the value for project.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.docker_image_url
     *
     * @return the value of project.docker_image_url
     *
     * @mbg.generated
     */
    public String getDockerImageUrl() {
        return dockerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.docker_image_url
     *
     * @param dockerImageUrl the value for project.docker_image_url
     *
     * @mbg.generated
     */
    public void setDockerImageUrl(String dockerImageUrl) {
        this.dockerImageUrl = dockerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.docker_image_tag
     *
     * @return the value of project.docker_image_tag
     *
     * @mbg.generated
     */
    public String getDockerImageTag() {
        return dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.docker_image_tag
     *
     * @param dockerImageTag the value for project.docker_image_tag
     *
     * @mbg.generated
     */
    public void setDockerImageTag(String dockerImageTag) {
        this.dockerImageTag = dockerImageTag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.container_port
     *
     * @return the value of project.container_port
     *
     * @mbg.generated
     */
    public Integer getContainerPort() {
        return containerPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.container_port
     *
     * @param containerPort the value for project.container_port
     *
     * @mbg.generated
     */
    public void setContainerPort(Integer containerPort) {
        this.containerPort = containerPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.host_port
     *
     * @return the value of project.host_port
     *
     * @mbg.generated
     */
    public Integer getHostPort() {
        return hostPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.host_port
     *
     * @param hostPort the value for project.host_port
     *
     * @mbg.generated
     */
    public void setHostPort(Integer hostPort) {
        this.hostPort = hostPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.is_deleted
     *
     * @return the value of project.is_deleted
     *
     * @mbg.generated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.is_deleted
     *
     * @param isDeleted the value for project.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column project.container_environment_variables
     *
     * @return the value of project.container_environment_variables
     *
     * @mbg.generated
     */
    public String getContainerEnvironmentVariables() {
        return containerEnvironmentVariables;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.container_environment_variables
     *
     * @param containerEnvironmentVariables the value for project.container_environment_variables
     *
     * @mbg.generated
     */
    public void setContainerEnvironmentVariables(String containerEnvironmentVariables) {
        this.containerEnvironmentVariables = containerEnvironmentVariables;
    }
}
