package net.averak.cap.adapter.dao.mapper.base;

import java.util.List;
import net.averak.cap.adapter.dao.entity.base.CronJobEntity;
import net.averak.cap.adapter.dao.entity.base.CronJobExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CronJobBaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    long countByExample(CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int deleteByExample(CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int insert(CronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int insertSelective(CronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    List<CronJobEntity> selectByExampleWithBLOBsWithRowbounds(CronJobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    List<CronJobEntity> selectByExampleWithBLOBs(CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    List<CronJobEntity> selectByExampleWithRowbounds(CronJobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    List<CronJobEntity> selectByExample(CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    CronJobEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CronJobEntity row, @Param("example") CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") CronJobEntity row, @Param("example") CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CronJobEntity row, @Param("example") CronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cron_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CronJobEntity row);
}
