package net.averak.cap.adapter.dao.mapper.base;

import java.util.List;
import net.averak.cap.adapter.dao.entity.base.MaintenanceEntity;
import net.averak.cap.adapter.dao.entity.base.MaintenanceExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface MaintenanceBaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    long countByExample(MaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int deleteByExample(MaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int insert(MaintenanceEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int insertSelective(MaintenanceEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    List<MaintenanceEntity> selectByExampleWithRowbounds(MaintenanceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    List<MaintenanceEntity> selectByExample(MaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    MaintenanceEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MaintenanceEntity row, @Param("example") MaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MaintenanceEntity row, @Param("example") MaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MaintenanceEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * maintenance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaintenanceEntity row);
}
