package net.averak.cap.adapter.dao.mapper.base;

import java.util.List;
import net.averak.cap.adapter.dao.entity.base.ProjectEntity;
import net.averak.cap.adapter.dao.entity.base.ProjectExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ProjectBaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    long countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int insert(ProjectEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int insertSelective(ProjectEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    List<ProjectEntity> selectByExampleWithRowbounds(ProjectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    List<ProjectEntity> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    ProjectEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProjectEntity row, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProjectEntity row, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectEntity row);
}
