package net.averak.cap.adapter.dao.mapper.base;

import java.util.List;
import net.averak.cap.adapter.dao.entity.base.ProjectCronJobEntity;
import net.averak.cap.adapter.dao.entity.base.ProjectCronJobExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ProjectCronJobBaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    long countByExample(ProjectCronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectCronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int insert(ProjectCronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int insertSelective(ProjectCronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    List<ProjectCronJobEntity> selectByExampleWithRowbounds(ProjectCronJobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    List<ProjectCronJobEntity> selectByExample(ProjectCronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    ProjectCronJobEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProjectCronJobEntity row, @Param("example") ProjectCronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProjectCronJobEntity row, @Param("example") ProjectCronJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectCronJobEntity row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * project_cron_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectCronJobEntity row);
}
