name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    # CI上でdocker-composeを起動する方法もあるが、`user: 1000:1000`を指定するとCIが落ちるのでCI用のMySQLとRedisを起動する
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_USER: db
          MYSQL_PASSWORD: db
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: backend test
        run: |
          ./gradlew test -x build

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: backend lint
        run: |
          ./gradlew spotlessCheck